// src/components/layout/Navbar.tsx
import React from 'react';
import { Bell, Menu, Package, Settings, User } from 'lucide-react';

const Navbar: React.FC = () => {
  return (
    <nav className="bg-white shadow-lg">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex justify-between h-16">
          <div className="flex items-center">
            <div className="flex-shrink-0 flex items-center">
              <Package className="h-8 w-8 text-blue-600" />
              <span className="ml-2 text-xl font-bold text-gray-800">Gogo Export 2.0</span>
            </div>
          </div>

          <div className="flex items-center">
            <button className="p-2 rounded-full hover:bg-gray-100">
              <Bell className="h-6 w-6 text-gray-600" />
            </button>
            <button className="p-2 rounded-full hover:bg-gray-100 ml-2">
              <Settings className="h-6 w-6 text-gray-600" />
            </button>
            <div className="ml-3 relative">
              <div className="flex items-center">
                <button className="flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                  <span className="sr-only">Open user menu</span>
                  <div className="h-8 w-8 rounded-full bg-blue-600 flex items-center justify-center">
                    <User className="h-5 w-5 text-white" />
                  </div>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

// components/NavBar.vue
<template>
  <nav class="bg-white shadow-lg">
    <div class="container mx-auto px-4">
      <div class="flex justify-between items-center h-16">
        <div class="flex items-center">
          <NuxtLink to="/" class="flex items-center">
            <img src="/logo.svg" alt="Gogo Express" class="h-8 w-auto" />
            <span class="ml-2 text-xl font-bold text-gray-800">Gogo Express Business</span>
          </NuxtLink>
        </div>
        <div class="flex items-center space-x-4">
          <NuxtLink to="/" class="text-gray-600 hover:text-gray-900">
            <Icon name="heroicons:home" class="w-6 h-6" />
          </NuxtLink>
          <NuxtLink to="/login" class="text-gray-600 hover:text-gray-900">
            <Icon name="heroicons:user" class="w-6 h-6" />
          </NuxtLink>
        </div>
      </div>
    </div>
  </nav>
</template>
